[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$oNQ6Z4wxRmgtJeS8tzZGqA$cGbyRzn0CKEK6r4uwsisFpum0dtpKSTimdQiY32m1Xda./fTxC3pUoBV/g60zDFZZxw8g.HLp/xDix0UFZVmng
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
